[project]
name = "yolo-foodseg"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "kagglehub>=0.3.12",
    "opencv-python>=4.11.0.86",
    "pyyaml>=6.0.2",
    "tqdm>=4.67.1",
    "ultralytics>=8.3.158",
]
